module.exports = {
  START: 'START',
  HELP: 'HELP',
  CHECK_ACTIVE: 'CHECK_ACTIVE',
  CHECK_DISABLED: 'CHECK_DISABLED',
  SUBSCRIBE_MENU: 'SUBSCRIBE_MENU',
  MY_SUBSCRIPTIONS: 'MY_SUBSCRIPTIONS',
  TOGGLE_REGION: 'TOGGLE_REGION',
};
